
CREATE SCHEMA "MORTGAGE";

CREATE TABLE "MORTGAGE"."MORTGAGE_APPLICANT" (
		"ID" INTEGER, 
		"NAME" VARCHAR(50 OCTETS), 
		"STREET_ADDRESS" VARCHAR(50 OCTETS), 
		"CITY" VARCHAR(30 OCTETS), 
		"STATE" VARCHAR(25 OCTETS), 
		"STATE_CODE" VARCHAR(5 OCTETS), 
		"ZIP_CODE" VARCHAR(9 OCTETS), 
		"EMAIL_ADDRESS" VARCHAR(40 OCTETS), 
		"PHONE_NUMBER" VARCHAR(17 OCTETS), 
		"GENDER" VARCHAR(6 OCTETS), 
		"SOCIAL_SECURITY_NUMBER" VARCHAR(16 OCTETS), 
		"EDUCATION" VARCHAR(20 OCTETS), 
		"EMPLOYMENT_STATUS" VARCHAR(13 OCTETS), 
		"MARITAL_STATUS" VARCHAR(8 OCTETS)
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE;

CREATE TABLE "MORTGAGE"."MORTGAGE_CUSTOMER" (
		"ID" INTEGER, 
		"INCOME" INTEGER, 
		"APPLIEDONLINE" VARCHAR(3 OCTETS), 
		"RESIDENCE" VARCHAR(28 OCTETS), 
		"YRS_AT_CURRENT_ADDRESS" SMALLINT, 
		"YRS_WITH_CURRENT_EMPLOYER" SMALLINT, 
		"NUMBER_OF_CARDS" SMALLINT, 
		"CREDITCARD_DEBT" SMALLINT, 
		"LOANS" SMALLINT, 
		"LOAN_AMOUNT" SMALLINT
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE;

CREATE TABLE "MORTGAGE"."MORTGAGE_DEFAULT" (
		"ID" INTEGER, 
		"MORTGAGE_DEFAULT" VARCHAR(3 OCTETS)
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE;

CREATE TABLE "MORTGAGE"."MORTGAGE_PROPERTY" (
		"ID" INTEGER, 
		"SALEPRICE" INTEGER, 
		"LOCATION" VARCHAR(4 OCTETS)
	)
	ORGANIZE BY COLUMN
	DATA CAPTURE NONE;

