
CREATE SCHEMA "MORTGAGE";

CREATE TABLE "MORTGAGE"."MORTGAGE_APPLICANT" (
		"ID" INTEGER, 
		"NAME" VARCHAR(50), 
		"STREET_ADDRESS" VARCHAR(50), 
		"CITY" VARCHAR(30), 
		"STATE" VARCHAR(25), 
		"STATE_CODE" VARCHAR(5), 
		"ZIP_CODE" VARCHAR(9), 
		"EMAIL_ADDRESS" VARCHAR(40), 
		"PHONE_NUMBER" VARCHAR(17), 
		"GENDER" VARCHAR(6), 
		"SOCIAL_SECURITY_NUMBER" VARCHAR(16), 
		"EDUCATION" VARCHAR(20), 
		"EMPLOYMENT_STATUS" VARCHAR(13), 
		"MARITAL_STATUS" VARCHAR(8)
	);

CREATE TABLE "MORTGAGE"."MORTGAGE_CUSTOMER" (
		"ID" INTEGER, 
		"INCOME" INTEGER, 
		"APPLIEDONLINE" VARCHAR(3), 
		"RESIDENCE" VARCHAR(28), 
		"YRS_AT_CURRENT_ADDRESS" SMALLINT, 
		"YRS_WITH_CURRENT_EMPLOYER" SMALLINT, 
		"NUMBER_OF_CARDS" SMALLINT, 
		"CREDITCARD_DEBT" SMALLINT, 
		"LOANS" SMALLINT, 
		"LOAN_AMOUNT" SMALLINT
	);

CREATE TABLE "MORTGAGE"."MORTGAGE_DEFAULT" (
		"ID" INTEGER, 
		"MORTGAGE_DEFAULT" VARCHAR(3)
	);

CREATE TABLE "MORTGAGE"."MORTGAGE_PROPERTY" (
		"ID" INTEGER, 
		"SALEPRICE" INTEGER, 
		"LOCATION" VARCHAR(16)
	);

