apiVersion: apps/v1
kind: Deployment
metadata:
  name: supp-db2
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: supp-db2
  template:
    metadata:
      labels:
        app: supp-db2
    spec:
      containers:
      - name: db2
        image: image-registry.openshift-image-registry.svc:5000/zen/db2
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 50000
        env:
        - name: LICENSE
          value: "accept"
        - name: DB2INST1_PASSWORD
          value: "passw0rd"
        - name: DBNAME
          value: "db"
        - name: DB2INSTANCE
          value: "db2inst1"
        volumeMounts:
        - mountPath: /database
          name: db2data
        securityContext:
          privileged: true
      securityContext:
        fsGroup: 1000
      serviceAccount: supp-db2-sa
      serviceAccountName: supp-db2-sa
      volumes:
      - name: db2data
        persistentVolumeClaim:
          claimName: supp-db2-pvc
