apiVersion: v1
kind: Service
metadata:
  labels:
    app: supp-db2
  name: supp-db2-svc
  namespace: zen
spec:
  ports:
  - name: db2-port
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: supp-db2
  sessionAffinity: None
  clusterIP: None

