kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: supp-db2-pvc
  namespace: zen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-storage-provisioner

