
CREATE INDEX ifxdemo1_ix1 ON ifxdemo1(F)
  FRAGMENT BY EXPRESSION
  PARTITION part_0 (F=-1.0) IN rootdbs INDEX OFF,
  PARTITION part_1 REMAINDER IN work1;

CREATE INDEX ifxdemo2_ix1 ON ifxdemo2(F)
  FRAGMENT BY EXPRESSION
  PARTITION part_0 (F=-1.0) IN rootdbs INDEX OFF,
  PARTITION part_1 REMAINDER IN work1;

CREATE INDEX ifxdemo3_ix1 ON ifxdemo3(F)
  FRAGMENT BY EXPRESSION
  PARTITION part_0 (F=-1.0) IN rootdbs INDEX OFF,
  PARTITION part_1 REMAINDER IN work1;

CREATE INDEX ifxdemo4_ix1 ON ifxdemo4(F)
  FRAGMENT BY EXPRESSION
  PARTITION part_0 (F=-1.0) IN rootdbs INDEX OFF,
  PARTITION part_1 REMAINDER IN work1;
