-- Simple table structure for dummy workload generator

CREATE TABLE ifxdemo1 (
  A INTEGER NOT NULL,
  B VARCHAR(100) NOT NULL,
  C VARCHAR(100) NOT NULL,
  D DATETIME YEAR TO FRACTION NOT NULL,
  PRIMARY KEY(A) CONSTRAINT ifxdemo1_pk
);

CREATE TABLE ifxdemo2 (
  A INTEGER NOT NULL,
  B VARCHAR(100) NOT NULL,
  C VARCHAR(100) NOT NULL,
  D DATETIME YEAR TO FRACTION NOT NULL,
  PRIMARY KEY(A) CONSTRAINT ifxdemo2_pk
);

CREATE TABLE ifxdemo3 (
  A INTEGER NOT NULL,
  B VARCHAR(100) NOT NULL,
  C VARCHAR(100) NOT NULL,
  D DATETIME YEAR TO FRACTION NOT NULL,
  PRIMARY KEY(A) CONSTRAINT ifxdemo3_pk
);

CREATE TABLE ifxdemo4 (
  A INTEGER NOT NULL,
  B VARCHAR(100) NOT NULL,
  C VARCHAR(100) NOT NULL,
  D DATETIME YEAR TO FRACTION NOT NULL,
  PRIMARY KEY(A) CONSTRAINT ifxdemo4_pk
);

-- End Of File
